name: Build EnableTLS.exe

on:
  workflow_dispatch:   # تشغيل يدوي فقط

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Compile EnableTLS.c
      run: |
        gcc tools/EnableTLS/EnableTLS.c -o EnableTLS.exe -ladvapi32
      shell: cmd

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: enabletls-exe
        path: EnableTLS.exe
