name: Build Windows Executable

on:
  workflow_dispatch:   # تشغيل يدوي فقط

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        cache: true

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      shell: bash

    - name: Build
      run: |
        cd build
        mingw32-make -j$(nproc)
      shell: bash

    - name: Deploy Qt dependencies (windeployqt)
      run: |
        cd build
        windeployqt.exe rssreader.exe
      shell: bash

    - name: Copy resources and translations
      run: |
        cd build
        cp -r ../resources .
        cp -r ../translations .
      shell: bash

    - name: Upload Deployed Folder
      uses: actions/upload-artifact@v4
      with:
        name: windows-deployed
        path: build/
